name: Hello world
on:
  push:
    branches:
       - main
jobs:
  first-hellow-world-job:
     runs-on: ubuntu-latest
     steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: Print Message
          run: echo "hello world GA testing"
     run-pytest:
        runs-on: ubuntu-latest
        steps:
          - run: checkout code
            uses: actions/checkout@v3
          - name: Setup python
            uses: actions/setup-python@v3
            with:
              python-version: 3.0
          - name: Install dependencies
            run:
              python -m pip install --upgrade pip
              pip install pytest
          - name: Run testcases
            run: pytest
