name: Hello world
on:
  push:
    branches:
       - main
jobs:
  first-hellow-world-job:
     runs-on: ubuntu-latest
     steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: Print Message
          run: echo "hello world GA testing"
